import { CardInfoType } from './types'

export const OBJECTS_INFO: CardInfoType[] = [
    {
        ObjectId: 1,
        ObjectName: "Папка 1",
        ObjectType: "FOLDER",
        ObjectIsFavorites: false,
        ObjectIsShared: false,
        ObjectIsAccess: true,
        ownerName: "Лев Бедняков",
        ownerEmail: "levbednyako3000@gmail.com",
        dateOfCreating: "15.07.2024",
    },
    {
        ObjectId: 2,
        ObjectName: "Папка 2",
        ObjectType: "FOLDER",
        ObjectIsFavorites: true,
        ObjectIsShared: false,
        ObjectIsAccess: true,
        ownerName: "Лев Бедняков",
        ownerEmail: "levbednyako3000@gmail.com",
        dateOfCreating: "15.07.2024",
    },
    {
        ObjectId: 3,
        ObjectName: "Дашборд 1",
        ObjectType: "DASHBOARD",
        ObjectIsFavorites: false,
        ObjectIsShared: false,
        ObjectIsAccess: true,
        ownerName: "Лев Бедняков",
        ownerEmail: "levbednyako3000@gmail.com",
        dateOfCreating: "15.07.2024",
    },
    {
        ObjectId: 4,
        ObjectName: "Дашборд 2",
        ObjectType: "DASHBOARD",
        ObjectIsFavorites: false,
        ObjectIsShared: false,
        ObjectIsAccess: true,
        ownerName: "Лев Бедняков",
        ownerEmail: "levbednyako3000@gmail.com",
        dateOfCreating: "15.07.2024",
    },
    {
        ObjectId: 5,
        ObjectName: "Папка 3",
        ObjectType: "FOLDER",
        ObjectIsFavorites: true,
        ObjectIsShared: true,
        ObjectIsAccess: true,
        ownerName: "Лев Бедняков",
        ownerEmail: "levbednyako3000@gmail.com",
        dateOfCreating: "15.07.2024",
    },
    {
        ObjectId: 6,
        ObjectName: "Папка 4",
        ObjectType: "FOLDER",
        ObjectIsFavorites: false,
        ObjectIsShared: false,
        ObjectIsAccess: false,
        ownerName: "Лев Бедняков",
        ownerEmail: "levbednyako3000@gmail.com",
        dateOfCreating: "15.07.2024",
    },
    {
        ObjectId: 7,
        ObjectName: "Папка 5",
        ObjectType: "FOLDER",
        ObjectIsFavorites: false,
        ObjectIsShared: false,
        ObjectIsAccess: true,
        ownerName: "Лев Бедняков",
        ownerEmail: "levbednyako3000@gmail.com",
        dateOfCreating: "15.07.2024",
    },
    {
        ObjectId: 8,
        ObjectName: "Папка 6",
        ObjectType: "FOLDER",
        ObjectIsFavorites: false,
        ObjectIsShared: true,
        ObjectIsAccess: true,
        ownerName: "Лев Бедняков",
        ownerEmail: "levbednyako3000@gmail.com",
        dateOfCreating: "15.07.2024",
    },

];