export const ADD_OBJECT = 'ADD_OBJECT';
export const REMOVE_OBJECT = 'REMOVE_OBJECT';
export const UPDATE_OBJECT = 'UPDATE_OBJECT';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const SET_SHARED_STATUS = 'SET_SHARED_STATUS';
export const SET_ACCESS_STATUS = 'SET_ACCESS_STATUS';

export const SEARCH_OBJECTS = 'SEARCH_OBJECTS';

export const APPLY_FILTERS = 'APPLY_FILTERS';
export const FILTER_BY_FAVORITES = 'FILTER_BY_FAVORITES';
export const FILTER_BY_SHARED = 'FILTER_BY_SHARED';
export const FILTER_BY_PERSON = 'FILTER_BY_PERSON';
export const FILTER_BY_COMPANY = 'FILTER_BY_COMPANY';